
sudo: required
services:
  - docker
dist: trusty

language: python
python:
- '2.7'
- '3.6'

env:
  global:
    - BINTRAY_USER=remia
    - BINTRAY_ORG=remiac
    - BINTRAY_REPO=Clairmeta_remiac_test
    - secure: "wE2TXo153zVlj0aeVIeA2FdGRHJuw3tgV2iDmnoESOcCp757V/4JkCJ/hnlWiPFScWsI+n3OjRXD03EKN2Hh7eiRJn9rtGYwtGia0A9hkwjUWfzkWwd+lE3qiAbe/Pag3HQZTz8HbILBzoVoLuBKr91WAAbAK9oV59exzuY3BmEdUPr/2WDz9hgSomsJ5fZ1Ak2MsNKyf9QnYQtR1p8v+zFaGTZNarPGSGqdcNdC60jU68WGj+fV/6DWNkYudzMWdM+EsVdYV04Ohz1j8BDPUM9jLUnQgxzI/KAfJab180cqcv6MT9exZR5NkqEeCU8/7rxscdsbrMfFsm/z86ZuJvgC3c/NDAFg/BDU9uo7uaFdeftqgkgiGwUxGIUGMD7Cj/lHWeyjKc8E6U5K/Q40uRdb87nQOPOWwSRzwqaXlWBq2KYZoliA6FM7S3gl2yFWD/fgVnuRI+lLwZVQdlmJ7Nyk+9IgQ4sLzSjULHk6QFzGAX6vH4MowdASbkziW8YlMyL0pBKU1mQwAEaZmxGNicNno/B2YpMg63uCa9KoRh4EfiIveTmz/BuHnThxQ9Pny/QrrXDO/P2Isifak/XcxMPQ7QvtT5fvVEnYvU9uAcbhodyYS72Pu6t7REgqPXE6JBsgfUR6r+duEJ3GTAJLwlOikru++iHWwGIEczdLGLQ="

install:
- pip install pipenv
- pipenv install
- pipenv check

# This belong to default stage 'test'
script:
- pipenv run python -m compileall clairmeta
- pipenv run python -m unittest discover -s tests

# Stage conditions
stages:
  - name: test
    if: type IN (pull_request) OR tag =~ ^1
  - name: deploy
    if: tag =~ ^1
  - name: packaging
    if: tag =~ ^pkg

# Jobs
jobs:
  include:
  - stage: packaging
    script:
    - /bin/bash .travis/build_env.sh
  - stage: deploy
    script:
    - echo "Deploying..."
    - python setup.py sdist bdist_wheel
    deploy:
      - provider: releases
        skip_cleanup: true
        api_key:
          secure:     NnuZ3rpD3VgJ+E0SQvfkP23SWyml4z/QBWJMHbT1mnacS7QPHYmg4kU3NBjd4RCXAorwD/PRZoexcISZsyaok2h5ck/Y7nNkQzzE6m+qBSOb4G/ae1+La6X8KuvuxqvJb9t084lwHdmPfTCLE32dz3IYf1ZHmQJ3kKOV0tPK+GgBEEr/tgyKQ38ktCGEq5Fg52zfzOgiPWkmkp9PZjuZBf47FpXAUj8jrkcgFLJmWVek7qd9igDLcO7RVISTLWlpgc/OLKIyiiOfXywPZcGlN6zI3ynR8DpyQ0gV0wsVacAwxuLKpZ3Ill93wvclOhIMQdGfOhLyOV1UyC8ud/nBGh9ScaP7UR0gAsJqile3huRHgwV2tgXbkExUy2zpEo/jn7CbBMCh2Wt6TJSeQZolN6eimgs3Io0Jke+w6W29WCPzhntNpwWtI6KbK8s/VCH9pD5uSwTMBUeAPQpj/2XV6SDfgHZkP7m2qZeRFTxwr4Af9W6l7otwF8d2VdxCbpitMUwviQeZrWbaacevBXJlri+W/XH/vFxo1LHJeETYpg+663rlqApCt+UpMyBP3cd4pNzddCY2PUycjWuwu9SDtf180iK4Sj4gsllYm2D5xG1YmZnCqw5xzXthTgZ+MpbF/619dNLZQxfJDBMchj9wBNiFpHKOoJPerIHHqs132hA=
        file_glob: true
        file: dist/*
        on:
          branch: master
          tags: true
      - provider: pypi
        skip_cleanup: true
        user: ymagis
        password:
          secure: z+NBy5v4tPyROoqiZhtlPPmFYPJj8UB8cBmr0Yu2ka3+Zp+w/ouiQJTY8jZgMs0vvQ96DaGhC1OYVKdN2hV+vvzwfeZHmDbqMG5FAEeFndmnAwMnSrK02Ux6x5RVme90ji9x1fQYjG1eo+opSjm36QI8Lj7r8OXXdCsWumstpGeFQ1z9LrP5/5eGMXHYniFLJoDIWmR3oBxngxtj+2hbFOhTDfxSzfkNH6XLmNcGoUbpTYrmFNjHQtQod4OL25ZmWJjD01sxKXW9q/BIrUVHmGGoXnMtUPJGRm/LN0+3FOllJouhKd+GcLFW2eBQwRG4w3Ztz3M6PYXKt9ayI/Xb/zfspxq55qq3+s+wR94ZzgVWWydH1d1v0BIwrHs/mR9aBpHxuFa1nu4BRz3hLonVuw9/h96KmaFfhjthhVspNq4YnV6gzJmxenz0trI9JZxkjA+x33QUf3/zaKM1k+9zJESCng8KZWlDqxF41HSEFA+ZaYic9dH9fFc88VCXIQ1dyswOkuncPNPi7Dcj09IoKbyUqOlUFCFa3vb4YDtMt/ZAGnTR3KkLQjkJqTyQ6z5TC8Nwn+BM+vC9df3ckxv+ogyPM/YILlcEFmEl2PV2k0xUv62s1t08sU0eSB3WVewuNQwrkQt4OYwhjaHYKb0ThlHY74kyOaiSV4C5ygtd/S8=
        distributions: sdist bdist_wheel
        on:
          branch: master
          tags: true